language: common-lisp
sudo: false

addons:
  apt:
    sources:
      - sourceline: 'deb http://http.us.debian.org/debian testing main'
    packages:
      - sbcl

cache:
  directories:
    - $HOME/.config/common-lisp

install:
  - bin/qi -i prove

script:
  - make t
