{include resources/header.md}
{set-property title "Trivial Shell User's Guide"}
{set-property docs-package trivial-shell}

# Trivial-Shell User's Guide

## Introduction

It's not much a guide, but it's here!

<div class='reference'>
    
## Reference

{docs shell-command}
{docs os-process-id}
{docs get-env-var}

</div>

## Indices

{docs-index :all}

<hr>

{include resources/footer.md}
